fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        confirmation:
            enabled: true
            from_email:
                address:        webmaster@example.com
                sender_name:    webmaster
            template:   FOSUserBundle:Registration:email.txt.twig
    resetting:
        token_ttl: 86400
        email:
            from_email:
                address: "%mailer_user%"
                sender_name: "%mailer_user%"
            template:   FOSUserBundle:Resetting:email.txt.twig
        form:
            type:               FOS\UserBundle\Form\Type\ResettingFormType
            name:               fos_user_resetting_form
    service:
        mailer:             fos_user.mailer.noop