lexik_jwt_authentication:
    secret_key:       '%jwt_private_key_path%' # required for token creation
    public_key:       '%jwt_public_key_path%'  # required for token verification
    pass_phrase:      '%jwt_key_pass_phrase%'  # required for token creation
    token_ttl:        '%jwt_token_ttl%'